language: php

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
